### ISSUE TITLE
Options view height too small

### ISSUE THREAD

**Issue by tnmyk** [asheeeshh/ohmypoll#1]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/73903781/178293846-ecc30b4d-0047-4d07-bb56-95b31b4b039b.png">

imo it will be harder to see all the options in a small container with scroll. 
Maybe render all the options without scroll, stacked?

**Comment by asrvd** [comment]
> <img alt="image" width="668" src="https://user-images.githubusercontent.com/73903781/178293846-ecc30b4d-0047-4d07-bb56-95b31b4b039b.png">
> 
> imo it will be harder to see all the options in a small container with scroll. Maybe render all the options without scroll, stacked?

that's quite weird as the container is large enough to hold at least 3 options 🤔 , is the viewport height causing this to happen

![image](https://user-images.githubusercontent.com/68690233/178296924-2a368c70-2cff-4e44-81cc-03ed318ba6c6.png)

**Comment by asrvd** [comment]
confirmed the bug on smaller viewport, will try to remove it, rendering all of them stacked is  sure an option but for some reason it doesnt look that good 🤔

**Comment by tnmyk** [comment]
Yea if it renders around at least 3 that it will look fine then 😁.
I can make a PR.

**Comment by asrvd** [comment]
> Yea if it renders around at least 3 that it will look fine then 😁. I can make a PR.

would be great if you can do it, i'm a little preoccupied in other things atm, thanks 👍🏼
